apiVersion: "kubernetes.cni.cncf.io/v1"
kind: Network
metadata:
  name: flannel-net
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "flannel",
    "delegate": {
      "isDefaultGateway": true
    }
  }'
