---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: virt-device-plugin
  namespace: kube-system

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-virt-device-plugin-amd64
  namespace: kube-system
  labels:
    tier: node
    app: virtdp
spec:
  template:
    metadata:
      labels:
        tier: node
        app: virtdp
    spec:
      hostNetwork: true
      hostPID: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: virt-device-plugin
      containers:
      - name: kube-virtdp
        image: nfvpe/virtdp:latest
        args:
        - --log-dir=virtdp
        - --log-level=10
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: false
        volumeMounts:
        - name: devicesock
          mountPath: /var/lib/kubelet/device-plugins/
          readOnly: false
        - name: net
          mountPath: /sys/class/net
          readOnly: true
        - name: log
          mountPath: /var/log
      volumes:
        - name: devicesock
          hostPath:
            path: /var/lib/kubelet/device-plugins/
        - name: net
          hostPath:
            path: /sys/class/net
        - name: log
          hostPath:
            path: /var/log
